USE startersql;
SELECT COUNT(*) FROM users;
SELECT COUNT(*) FROM users WHERE gender = 'female';
SELECT COUNT(*) FROM users WHERE gender = 'male';
SELECT MIN(salary) AS min_salary, MAX(salary) AS max_salary FROM users;
SELECT SUM(salary) AS Total FROM users;
SELECT gender, AVG(salary) AS ave_salary FROM users GROUP BY gender;
SELECT gender, SUM(salary) AS ave_salary FROM users GROUP BY gender;
SELECT name, LENGTH(name) AS name_length FROM users;
SELECT name, LENGTH(name) AS name_length FROM USERS ORDER BY LENGTH(name) ASC LIMIT 1;
SELECT name, LENGTH(name) AS name_length FROM USERS ORDER BY LENGTH(name) DESC LIMIT 1;
SELECT id, gender, LOWER(name) AS lower_name, LENGTH(name) AS len_name FROM users;
SELECT id, gender, UPPER(name) AS upper_name, LENGTH(name) AS len_name FROM users;
SELECT id, gender, LOWER(name) AS lower_name, CONCAT(LOWER(name), '123') AS username FROM users;
SELECT id, gender, LOWER(name) AS lower_name, CONCAT(LOWER(name), '123') AS username, NOW() AS time FROM users;
SELECT id, gender, LOWER(name) AS lower_name, CONCAT(LOWER(name), '123') AS username, YEAR(CURDATE()) AS time FROM users;
SELECT id, gender, LOWER(name) AS lower_name, CONCAT(LOWER(name) , '123') AS username, YEAR(date_of_birth) AS time FROM users;
SELECT name, DATEDIFF(CURDATE(), date_of_birth) AS days FROM users;
SELECT name, TIMESTAMPDIFF(YEAR, date_of_birth, CURDATE()) AS age FROM users ORDER BY age DESC;
SELECT name, TIMESTAMPDIFF(YEAR, date_of_birth, CURDATE()) AS age FROM users ORDER BY age ASC;
SELECT salary,ROUND(salary) AS rounded,FLOOR(salary) AS floored,CEIL(salary) AS ceiled FROM users;
SELECT name, gender, IF(gender = 'Female', 'Yes', 'No') AS is_female FROM users;